language: go
go:
  - "1.14"
  - "1.15"
  - "tip"
notificaitons:
  email:
    recipients:
      gomatic@nicerobot.org
    on_success: change
    on_failure: always
script:
  - go env
  - go vet -mod=vendor ./...
  - go test -mod=vendor -v ./...
